ALTER TABLE merchants
ADD COLUMN IF NOT EXISTS pan_number VARCHAR(20),
ADD COLUMN IF NOT EXISTS gstin VARCHAR(20),
ADD COLUMN IF NOT EXISTS bank_account_number VARCHAR(50),
ADD COLUMN IF NOT EXISTS ifsc_code VARCHAR(15),
ADD COLUMN IF NOT EXISTS account_holder_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS business_type VARCHAR(50) DEFAULT 'PROPRIETORSHIP',
ADD COLUMN IF NOT EXISTS doc_pan_url TEXT,
ADD COLUMN IF NOT EXISTS doc_business_proof_url TEXT,
ADD COLUMN IF NOT EXISTS doc_bank_proof_url TEXT;
